### ISSUE TITLE
可以支持滚动后再显示吗？

### ISSUE THREAD

**Issue by jevantang** [mulook/weapp-navigation-bar#1]
感谢分享这么好的组件。

请问，我在全屏的时候，只有用户向上滚动页面后才会显示导航栏，这个组件支持吗？

场景是这样的，我原本是全屏页面，用户滚动浏览页面，然后顶部显示导航栏。

**Comment by mulook** [comment]
这个打算增加，因为滚动分page和scrollview两种不同的滚动事件，而且他们的滚事件只能写在page里，所以切换显示/隐藏需要在page里触发。

**Comment by jevantang** [comment]
> 这个打算增加，因为滚动分page和scrollview两种不同的滚动事件，而且他们的滚事件只能写在page里，所以切换显示/隐藏需要在page里触发。

期待

**Comment by mulook** [comment]
新版已经支持的，可以参考示例使用。[查看版本更新](https://github.com/mulook/weapp-navigation-bar/blob/master/CHANGELOG.md)

**Comment by jevantang** [comment]
> 新版已经支持的，可以参考示例使用。[查看版本更新](https://github.com/mulook/weapp-navigation-bar/blob/master/CHANGELOG.md)

感谢更新，刚才简单试了一下，没有成功，明天再研究一下。

我描述的功能可以参考「NIKE微主页」小程序，打开是不带导航栏的，用户滚动后才会显示导航栏。
