### ISSUE TITLE
滚动30像素切换显示隐藏  在安卓机上隐藏不全

### ISSUE THREAD

**Issue by songStar0904** [mulook/weapp-navigation-bar#3]
![image](https://user-images.githubusercontent.com/21984603/47281035-b08fd280-d60b-11e8-9fdb-2f8b8fdca5c0.png)

**Comment by songStar0904** [comment]
经测试， this.selectComponent("#navigationBar").toggleShow(); 这个接口固定偏移是64px  而安卓机是 48+20 =68px  这里有偏差4px。 这是官方的接口问题？

**Comment by songStar0904** [comment]
原因找到了 组件translateY 固定64px了  安卓有68px。

**Comment by mulook** [comment]
谢谢反馈，匆忙添加功能就上传了，忘了修改回动态值。可以把固定64修改成功，data里的paddingTop+height或下载新版使用。[查看更新](https://github.com/mulook/weapp-navigation-bar/blob/master/CHANGELOG.md)
