### ISSUE TITLE
可以监听导航栏'返回上一页'事件吗?

### ISSUE THREAD

**Issue by Nisus-Liu** [mulook/weapp-navigation-bar#6]
我先实现效果: 点击`返回上一页`时弹窗提示用户确认. 所以, 需要能够监控返回上一页的事件.
组件本身`navigateBack`的tap方法, 可以在这里弹窗提示. 但这会导致所有页面中的导航栏, 都会弹窗.
显然不合适.

不知道, 原生自定义组件能不能将某些事件抛出, 让父组件能够监听的到?

**Comment by mulook** [comment]
新版增加了提示弹窗的实现，但是不打算增加事件派送系统来增加该组件的复杂性，有需要可自行添加。[https://github.com/mulook/weapp-navigation-bar/blob/master/CHANGELOG.md](url)

**Comment by mulook** [comment]
新版支持用bind绑定返回事件，[查看使用方法](https://github.com/mulook/weapp-navigation-bar#%E7%BB%84%E4%BB%B6%E5%A4%96%E9%83%A8%E7%BB%91%E5%AE%9A%E4%BA%8B%E4%BB%B6%E8%AF%B4%E6%98%8E)
另外 Issue #5 这位网友早已提供解决方案。
